# ==========================================
# SERVER CONFIGURATION
# ==========================================
server.port=${PORT:8080}

# ==========================================
# SPRING APPLICATION CONFIGURATION
# ==========================================
spring.application.name=hotel-sistema-backend

# ==========================================
# DATASOURCE CONFIGURATION
# ==========================================
spring.datasource.url=jdbc:mysql://${DB_HOST:hayabusa.proxy.rlwy.net}:${DB_PORT:20503}/${DB_NAME:railway}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:NLsdKnrNJpljAxSFDjIurtDkmMfmpFik}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / HIBERNATE CONFIGURATION
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================================
# JWT CONFIGURATION
# ==========================================
jwt.secret=${JWT_SECRET:skldnaskodnjasndjnasjdnasjdnjas}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# ==========================================
# LOGGING CONFIGURATION
# ==========================================
logging.level.org.springframework.security=INFO
logging.level.com.hotelsistema.backend=DEBUG